steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build app image'
    entrypoint: docker
    args: ["build", "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/models/model-iris:latest", "-f", "serve/Dockerfile", "."]
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push app image'
    entrypoint: docker
    args: ["push", "europe-west1-docker.pkg.dev/$PROJECT_ID/models/model-iris", "--all-tags"]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args: [
      "run",
      "deploy",
      "model-iris",
      "--image=europe-west1-docker.pkg.dev/cloud-production-enrique/models/model-iris:latest",
      "--allow-unauthenticated",
      "--port=8080",
      "--region=europe-west1",
      "--project=$PROJECT_ID"
    ]